### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by atypicalinsomniac** [RiptideSage/OoT-CompletedChecks#1]
I am trying to run this with BizHawk and i am getting the error message 'NLua.Exceptions.LuaScriptException: [string "main"]:86: bad argument #2 to 'insert' (position out of bounds)'

any solution?

**Comment by RiptideSage** [comment]
Hey Insomniac,
I've pushed an update that should fix this.

I originally wrote the script for Bizhawk 2.8 which used Lua 5.1, and I suspect you're using BizHawk 2.9 which uses Lua 5.4 .
Turns out Lua 5.2 had several breaking changes to how Tables and integer math worked, but the new version should work.

If you're still experiencing the issue please leave a comment with your BizHawk version number and I'll look into it.

**Comment by atypicalinsomniac** [comment]
Confirmed working! Thank you so much!
